# Generated by Django 2.0.2 on 2018-04-21 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import microblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', microblog.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blogger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
